### ISSUE TITLE
S-1: List of all recipes

### ISSUE THREAD

**Issue by itsandeepsingh** [itsandeepsingh/capstone-project#1]
## Value proposition

**As a** hobby cook
**I want to** see a list of all recipes
**So that** I can get an overview of all recipes.

## Description
![Image](https://user-images.githubusercontent.com/132406870/251811462-39a875be-11db-4f83-86af-b205b609cbcc.png)

## Acceptance criteria

- [ ] All recipes are visible (at least three recipes)
- [ ] The placeholder "Sorry, no recipes found" is displayed if no recipes were found
The following elements are displayed for each recipe:
   - [ ]  Image (optional)
   - [ ]  Title (mandatory)
   - [ ]  Subtitle (optional)
- [ ] A default picture displayed, if there is no picture for the recipe

## Tasks
- [ ] Create the component **Recipes** for the list of recipes
- [ ] Create the component **Recipe** for a individual recipe
- [ ] Show a placeholder, if no recipes found 
- [ ] The component **Recipe** contains image, title and subtitle
- [ ] Create at least 3 recipes

**Comment by vaupunkt** [comment]
lgtm :)

**Comment by itsandeepsingh** [comment]
finish
