### ISSUE TITLE
S-2: [RecipesOverviewPage] Show working time and waiting time for each recipe

### ISSUE THREAD

**Issue by itsandeepsingh** [itsandeepsingh/capstone-project#2]
## Value proposition

**As a** hobby cook
**I want to** see the working time and waiting time for each recipe
**So that** I know how long I need in total for a recipe and it is easier for me to choose a recipe. 

## Description
It is necessary that the issue S-1 is closed.

![Image](https://user-images.githubusercontent.com/132406870/251825752-e6eea0b0-efc0-4451-a459-9d560221c612.png)

## Acceptance criteria

- [ ] For each recipe the working time and waiting time are shown 
- [ ] The times are placed  inside the picture of the recipe (left below)
- [ ] If there is no waiting time, the waiting time is not displayed

## Tasks
- [ ] Define a working time and waiting time for each recipe 
- [ ] Place the times inside the picture of the recipe (left below)

**Comment by tejue** [comment]
LGTM :)
