### ISSUE TITLE
S-3: [RecipesOverviewPage] Select recipes (multiselection)

### ISSUE THREAD

**Issue by itsandeepsingh** [itsandeepsingh/capstone-project#4]
## Value proposition

**As a** hobby cook
**I want to** select multiple recipes I want to cook
**So that** I can start cooking multiple recipes at the same time.
## Description
It is necessary that the issue S-1 is closed.
A button to start cooking will be built in with S-4. 

![Image](https://user-images.githubusercontent.com/132406870/252159264-8a25169b-d944-4bb3-9768-08527936bf86.png)

## Acceptance criteria

- [ ] There is a selection button at the top right of the page
- [ ] If the button has been clicked, the user can select multiple recipes
- [ ] A maximum of three recipes can be selected
- [ ] If the user is in selection mode and clicks on an image of a recipe, a hook in a round circle will turn up at the bottom right of the image of the recipe
- [ ] If the user is in selection mode and clicks on an image of a recipe that has already been selected, the hook disappears
- [ ] If the user is not in selection mode and clicks on an image of a recipe, nothing happens
- [ ] If the user is in selection mode, the button shows "Abbrechen", otherwise the button shows "Auswählen"
- [ ] The button should also be visible when scrolling
- [ ] When reloading the page, the selection of recipes should not be lost

## Tasks
- [ ] Add the component **SelectionButton**
- [ ] Add the component **RecipeSelection**
- [ ] The selection button should have the css position "fixed"
- [ ] Use a hook for the recipe selection 
- [ ] Add a function **handleToggleSelection**
- [ ] Add **isSelected** state to **Recipe** component

**Comment by tejue** [comment]
Hi Sandeep,
looks good to me. You could be a bit more specific on your tasks instead of just ... but your acceptance criteria look fine :)

**Comment by itsandeepsingh** [comment]
Thanks Teresa :)
